export interface DiagnosticTest {
  id: string;
  code: string;
  name: string;
  category: "Pathology" | "Radiology & Imaging" | "Cardiology" | "Ultrasound (USG)" | "Specialized & Endoscopy" | "Health Packages";
  price: number; // in BDT
  discountPrice?: number;
  sampleType: "Blood" | "Urine" | "Digital Imaging" | "Real-time Scan" | "Stool" | "Tissue" | "Non-Invasive";
  deliveryTime: string;
  preparation: string;
  homeSampleAvailable: boolean;
  description: string;
}

export const DEFAULT_DIAGNOSTIC_TESTS: DiagnosticTest[] = [
  // Pathology & Blood
  {
    id: "cbc-01",
    code: "PATH-CBC",
    name: "Complete Blood Count (CBC) with ESR",
    category: "Pathology",
    price: 450,
    discountPrice: 400,
    sampleType: "Blood",
    deliveryTime: "3-4 Hours (Same Day)",
    preparation: "No special fasting required. Stay hydrated.",
    homeSampleAvailable: true,
    description: "Evaluates overall health, detecting anemia, infections, leukemia, and platelet disorders.",
  },
  {
    id: "lipid-01",
    code: "PATH-LIPID",
    name: "Lipid Profile (Cholesterol, HDL, LDL, Triglycerides)",
    category: "Pathology",
    price: 1100,
    discountPrice: 950,
    sampleType: "Blood",
    deliveryTime: "Same Day (4-6 Hours)",
    preparation: "Strict 10-12 hours overnight fasting required. Water is permitted.",
    homeSampleAvailable: true,
    description: "Measures blood fats to evaluate cardiovascular risk, stroke propensity, and arterial plaque health.",
  },
  {
    id: "hba1c-01",
    code: "PATH-HBA1C",
    name: "HbA1c (Glycated Hemoglobin)",
    category: "Pathology",
    price: 900,
    discountPrice: 800,
    sampleType: "Blood",
    deliveryTime: "3-4 Hours",
    preparation: "No fasting required. Can be done anytime of day.",
    homeSampleAvailable: true,
    description: "Measures average blood sugar levels over the past 3 months for diabetic diagnosis and monitoring.",
  },
  {
    id: "fbs-01",
    code: "PATH-FBS",
    name: "Fasting Blood Sugar (FBS) & 2h ABF",
    category: "Pathology",
    price: 300,
    sampleType: "Blood",
    deliveryTime: "2-3 Hours",
    preparation: "8-10 hours fasting for the first sample, then 2 hours after breakfast for the second sample.",
    homeSampleAvailable: true,
    description: "Evaluates insulin glucose metabolism and monitors diabetes mellitus.",
  },
  {
    id: "tft-01",
    code: "PATH-TFT",
    name: "Thyroid Profile (TSH, FT3, FT4)",
    category: "Pathology",
    price: 1600,
    discountPrice: 1400,
    sampleType: "Blood",
    deliveryTime: "Same Day (Evening)",
    preparation: "Morning sample preferred before taking thyroid medications unless advised by physician.",
    homeSampleAvailable: true,
    description: "Assesses thyroid gland function, hyperthyroidism, hypothyroidism, and metabolic regulation.",
  },
  {
    id: "creat-01",
    code: "PATH-RFT",
    name: "Serum Creatinine & Kidney Function (RFT)",
    category: "Pathology",
    price: 550,
    sampleType: "Blood",
    deliveryTime: "2-3 Hours",
    preparation: "Avoid excessive meat consumption 24 hours prior. Normal hydration.",
    homeSampleAvailable: true,
    description: "Evaluates renal clearance and kidney filtration efficiency.",
  },
  {
    id: "lft-01",
    code: "PATH-LFT",
    name: "Liver Function Test (SGPT, SGOT, Bilirubin, Alk Phos)",
    category: "Pathology",
    price: 1200,
    discountPrice: 1050,
    sampleType: "Blood",
    deliveryTime: "4-5 Hours",
    preparation: "Overnight fasting of 8 hours recommended.",
    homeSampleAvailable: true,
    description: "Screens for liver inflammation, hepatitis, fatty liver, jaundice, and biliary clearance.",
  },
  {
    id: "vitd-01",
    code: "PATH-VITD",
    name: "Vitamin D (25-Hydroxy Vitamin D) & Vitamin B12",
    category: "Pathology",
    price: 3200,
    discountPrice: 2800,
    sampleType: "Blood",
    deliveryTime: "24 Hours",
    preparation: "Fasting not mandatory.",
    homeSampleAvailable: true,
    description: "Crucial for bone density, nerve transmission, immunity, and chronic fatigue evaluation.",
  },
  {
    id: "urine-01",
    code: "PATH-URINE",
    name: "Urine Routine & Microscopic Examination (R/M/E)",
    category: "Pathology",
    price: 250,
    sampleType: "Urine",
    deliveryTime: "2 Hours",
    preparation: "Clean-catch midstream urine sample in sterile container.",
    homeSampleAvailable: true,
    description: "Screens for urinary tract infections (UTI), proteinuria, hematuria, and renal calculi.",
  },

  // Radiology & Digital Imaging
  {
    id: "xray-01",
    code: "RAD-XRAY",
    name: "Digital X-Ray Chest P/A View (High Resolution)",
    category: "Radiology & Imaging",
    price: 600,
    sampleType: "Digital Imaging",
    deliveryTime: "1-2 Hours",
    preparation: "Remove metallic ornaments, jewelry, and metal-containing garments.",
    homeSampleAvailable: false,
    description: "Evaluates lungs, ribs, diaphragmatic contour, cardiomegaly, pneumonia, and tuberculosis.",
  },
  {
    id: "mri-01",
    code: "RAD-MRI-BR",
    name: "MRI Brain (1.5 Tesla / 3.0 Tesla High-Field)",
    category: "Radiology & Imaging",
    price: 6500,
    discountPrice: 5800,
    sampleType: "Digital Imaging",
    deliveryTime: "Same Day (4-6 Hours)",
    preparation: "No metallic implants, pacemakers, or piercings. 4 hours fasting if contrast indicated.",
    homeSampleAvailable: false,
    description: "Precision non-radiation imaging for neurological disorders, stroke, migraines, tumors, and aneurysms.",
  },
  {
    id: "ct-01",
    code: "RAD-CT-CH",
    name: "HRCT of Chest & Lungs (High Resolution CT)",
    category: "Radiology & Imaging",
    price: 5200,
    discountPrice: 4600,
    sampleType: "Digital Imaging",
    deliveryTime: "3-4 Hours",
    preparation: "4 hours fasting if intravenous contrast is prescribed by doctor.",
    homeSampleAvailable: false,
    description: "Detailed thin-slice volumetric pulmonary scanning for interstitial lung disease, asthma, and fibrosis.",
  },

  // Cardiology
  {
    id: "ecg-01",
    code: "CARD-ECG",
    name: "12-Lead Digital ECG (Electrocardiogram)",
    category: "Cardiology",
    price: 350,
    sampleType: "Non-Invasive",
    deliveryTime: "Instant (15-30 Minutes)",
    preparation: "Avoid physical exertion or caffeine immediately prior to the test.",
    homeSampleAvailable: false,
    description: "Records electrical cardiac impulses to screen for arrhythmias, ischemia, and infarction.",
  },
  {
    id: "echo-01",
    code: "CARD-ECHO",
    name: "2D Color Doppler Echocardiography",
    category: "Cardiology",
    price: 2400,
    discountPrice: 2100,
    sampleType: "Real-time Scan",
    deliveryTime: "1 Hour",
    preparation: "No fasting required. Wear comfortable loose-fitting clothing.",
    homeSampleAvailable: false,
    description: "Ultrasound assessment of cardiac valves, ejection fraction (EF%), chamber dimensions, and wall motion.",
  },
  {
    id: "ett-01",
    code: "CARD-ETT",
    name: "Exercise Tolerance Test (ETT / Treadmill Stress Test)",
    category: "Cardiology",
    price: 2800,
    sampleType: "Non-Invasive",
    deliveryTime: "Same Day",
    preparation: "Wear athletic footwear and comfortable garments. Light meal 2-3 hours prior.",
    homeSampleAvailable: false,
    description: "Measures cardiac performance, reserve, and ischemic threshold during graded exertion.",
  },

  // Ultrasound (USG)
  {
    id: "usg-01",
    code: "USG-ABD",
    name: "USG of Whole Abdomen with Pelvis",
    category: "Ultrasound (USG)",
    price: 1600,
    discountPrice: 1400,
    sampleType: "Real-time Scan",
    deliveryTime: "1-2 Hours",
    preparation: "Fasting for 6 hours prior. Drink 4-5 glasses of water 1 hour prior to keep bladder full.",
    homeSampleAvailable: false,
    description: "Examines liver, gallbladder, pancreas, spleen, kidneys, urinary bladder, prostate, and uterus.",
  },
  {
    id: "usg-02",
    code: "USG-PREG",
    name: "4D Pregnancy Anomaly Scan & Color Doppler",
    category: "Ultrasound (USG)",
    price: 2600,
    discountPrice: 2300,
    sampleType: "Real-time Scan",
    deliveryTime: "Same Day",
    preparation: "Full bladder required during first trimester. Moderate hydration later in pregnancy.",
    homeSampleAvailable: false,
    description: "High-resolution fetal anatomical survey to confirm developmental milestones and placental flow.",
  },

  // Specialized & Endoscopy
  {
    id: "endo-01",
    code: "GI-ENDO",
    name: "Video Upper GI Endoscopy",
    category: "Specialized & Endoscopy",
    price: 3800,
    discountPrice: 3400,
    sampleType: "Non-Invasive",
    deliveryTime: "Same Day",
    preparation: "Strict overnight fasting for at least 8 hours. No liquids in morning.",
    homeSampleAvailable: false,
    description: "Direct optical visualization of esophagus, stomach, and duodenum for ulcers and reflux.",
  },

  // Health Packages
  {
    id: "pkg-exec",
    code: "PKG-EXEC",
    name: "Executive Comprehensive Health Checkup Package",
    category: "Health Packages",
    price: 5800,
    discountPrice: 4500,
    sampleType: "Blood",
    deliveryTime: "24 Hours (Full Report + Doctor Review)",
    preparation: "10-12 hours overnight fasting. First morning urine required.",
    homeSampleAvailable: true,
    description: "Includes: CBC, Lipid Profile, Liver Panel, Kidney Panel, HbA1c, Thyroid (TSH), Serum Uric Acid, Urine R/M/E, Digital ECG, and Chest X-Ray.",
  },
  {
    id: "pkg-heart",
    code: "PKG-HEART",
    name: "Cardiovascular Cardiac Health Screening Panel",
    category: "Health Packages",
    price: 4900,
    discountPrice: 3900,
    sampleType: "Blood",
    deliveryTime: "Same Day",
    preparation: "Overnight fasting 10-12 hours.",
    homeSampleAvailable: true,
    description: "Includes: Digital ECG, 2D Color Echo, Lipid Profile, Blood Glucose, Serum Creatinine, Electrolytes, and Cardiologist Consultation.",
  },
];
