export interface CatalogItemTemplate {
  id: string;
  code: string;
  name: string;
  type: "CLINICAL_SERVICE" | "DIAGNOSTIC_TEST";
  category: string;
  defaultPrice: number; // in BDT (0 for non-billable or free emergency triage)
  defaultDiscountPrice?: number;
  sampleType?: string;
  deliveryTime?: string;
  preparation?: string;
  homeSampleAvailable?: boolean;
  description: string;
  iconName?: string; // e.g. 'HeartPulse', 'Ambulance', 'FlaskConical', 'Pill', 'Syringe', 'Sparkles', 'Activity', 'ShieldCheck', etc.
  badge?: string;
}

// Master Pre-built Template Library for Key Clinical Facilities & Services
export const DEFAULT_CLINICAL_SERVICES: CatalogItemTemplate[] = [
  {
    id: "serv-emg-247",
    code: "SERV-EMG-247",
    name: "24/7 Emergency & Trauma Unit",
    type: "CLINICAL_SERVICE",
    category: "Emergency & Critical Care",
    defaultPrice: 500,
    deliveryTime: "Immediate Round-the-Clock",
    preparation: "Emergency walk-in anytime. No prior appointment required.",
    homeSampleAvailable: false,
    description: "Equipped for urgent polytrauma, cardiac arrest resuscitation, acute stroke, and poisoning management.",
    iconName: "HeartPulse",
    badge: "24/7 Emergency",
  },
  {
    id: "serv-icu-ccu",
    code: "SERV-ICU-CCU",
    name: "Intensive Care Unit (ICU) & CCU Support",
    type: "CLINICAL_SERVICE",
    category: "Emergency & Critical Care",
    defaultPrice: 4500,
    deliveryTime: "Continuous Critical Monitoring",
    preparation: "Doctor referral required for patient admission.",
    homeSampleAvailable: false,
    description: "Multidisciplinary life support with high-end mechanical ventilators, invasive arterial lines, and dedicated intensivist staffing.",
    iconName: "Activity",
    badge: "Critical Care",
  },
  {
    id: "serv-nicu-picu",
    code: "SERV-NICU-PICU",
    name: "Neonatal & Pediatric Intensive Care (NICU/PICU)",
    type: "CLINICAL_SERVICE",
    category: "Pediatric & Maternal Care",
    defaultPrice: 3500,
    deliveryTime: "Continuous Neonatal Care",
    preparation: "Specialized incubators, phototherapy units, and neonatal ventilators.",
    homeSampleAvailable: false,
    description: "Advanced life-saving incubator care for premature, low-birth-weight, and critically ill newborns.",
    iconName: "Sparkles",
    badge: "Specialized",
  },
  {
    id: "serv-dialysis",
    code: "SERV-HEMO-DIAL",
    name: "Hemodialysis Unit (Per Session)",
    type: "CLINICAL_SERVICE",
    category: "Specialized Medical Services",
    defaultPrice: 2500,
    defaultDiscountPrice: 2200,
    deliveryTime: "4 Hours Session",
    preparation: "Prior nephrologist prescription, viral marker screening (HBsAg, Anti-HCV, HIV) mandatory.",
    homeSampleAvailable: false,
    description: "State-of-the-art dialysis machines with online hemodiafiltration and dedicated negative isolation stations.",
    iconName: "Activity",
    badge: "Renal Care",
  },
  {
    id: "serv-ambulance",
    code: "SERV-AMB-247",
    name: "24/7 ICU & Cardiac Ambulance Fleet",
    type: "CLINICAL_SERVICE",
    category: "Emergency & Critical Care",
    defaultPrice: 1500,
    deliveryTime: "Instant Dispatch",
    preparation: "Call facility emergency desk hotline for nearest coordinate dispatch.",
    homeSampleAvailable: false,
    description: "Advanced transport fleet fitted with portable ventilators, defib monitors, oxygen supply, and paramedic crew.",
    iconName: "Ambulance",
    badge: "Emergency Fleet",
  },
  {
    id: "serv-blood-bank",
    code: "SERV-BLOOD-BANK",
    name: "Safe Blood Bank & Component Separation Unit",
    type: "CLINICAL_SERVICE",
    category: "Clinical Laboratory & Blood",
    defaultPrice: 800,
    deliveryTime: "24 Hours Service",
    preparation: "Donor screening, cross-matching, and ELISA testing conducted.",
    homeSampleAvailable: false,
    description: "Whole blood, packed red cells, fresh frozen plasma (FFP), and platelet concentrates separation.",
    iconName: "Syringe",
    badge: "Life Saving",
  },
  {
    id: "serv-pharmacy-247",
    code: "SERV-PHARM-247",
    name: "24-Hour In-House Model Pharmacy",
    type: "CLINICAL_SERVICE",
    category: "Pharmacy & Dispensary",
    defaultPrice: 0,
    deliveryTime: "24/7 Over the counter & In-patient",
    preparation: "Valid registered doctor prescription for restricted scheduled drugs.",
    homeSampleAvailable: true,
    description: "100% authentic temperature-controlled temperature pharmaceuticals, emergency cardiac injections, and biologics.",
    iconName: "Pill",
    badge: "24/7 Pharmacy",
  },
  {
    id: "serv-physio",
    code: "SERV-PHYSIO",
    name: "Physiotherapy & Rehabilitation Center",
    type: "CLINICAL_SERVICE",
    category: "Rehabilitation & Therapy",
    defaultPrice: 800,
    defaultDiscountPrice: 700,
    deliveryTime: "45-60 Minutes Session",
    preparation: "Wear comfortable loose sportswear. Bring prior orthopedic/neuro reports.",
    homeSampleAvailable: true,
    description: "Post-stroke motor rehabilitation, sports injury ultrasound, traction, and posture realignment.",
    iconName: "Activity",
    badge: "Rehab",
  },
  {
    id: "serv-daycare-surgery",
    code: "SERV-DAY-SURG",
    name: "Day Care Surgery & Laparoscopic OT",
    type: "CLINICAL_SERVICE",
    category: "Surgical Suites",
    defaultPrice: 8000,
    deliveryTime: "Same Day Discharge",
    preparation: "Pre-anesthesia checkup (PAC) and overnight fasting required.",
    homeSampleAvailable: false,
    description: "Laminar airflow modular operation theaters for minimally invasive laparoscopic and eye surgeries.",
    iconName: "Sparkles",
    badge: "Surgical Suite",
  },
  {
    id: "serv-chemo-daycare",
    code: "SERV-CHEMO-DC",
    name: "Day Care Oncology Chemotherapy Infusion",
    type: "CLINICAL_SERVICE",
    category: "Specialized Medical Services",
    defaultPrice: 3000,
    deliveryTime: "Day Care Protocol",
    preparation: "Recent CBC, SGPT, and serum creatinine reports evaluated by medical oncologist.",
    homeSampleAvailable: false,
    description: "Dedicated laminar flow cytotoxic reconstitution and supervised intravenous chemotherapy infusions.",
    iconName: "Syringe",
    badge: "Oncology",
  },
  {
    id: "serv-home-nursing",
    code: "SERV-HOME-NURSE",
    name: "Home Nursing & Sample Collection Desk",
    type: "CLINICAL_SERVICE",
    category: "Home Health Care",
    defaultPrice: 400,
    deliveryTime: "Scheduled Slot",
    preparation: "Book at least 3 hours in advance via helpline.",
    homeSampleAvailable: true,
    description: "Qualified nurse visits for dressing, catheterization, cannula insertion, and diagnostic blood draws.",
    iconName: "ShieldCheck",
    badge: "Doorstep Care",
  },
  {
    id: "serv-corp-insurance",
    code: "SERV-CORP-INS",
    name: "Corporate & Health Insurance Cashless Desk",
    type: "CLINICAL_SERVICE",
    category: "Insurance & Billing",
    defaultPrice: 0,
    deliveryTime: "Immediate Authorization",
    preparation: "Present valid corporate health card and national identity document.",
    homeSampleAvailable: false,
    description: "Direct tie-ups with leading local & international health insurers and corporate benefit schemes.",
    iconName: "ShieldCheck",
    badge: "Cashless Desk",
  },
];

// Master Pre-built Template Library for Diagnostic & Pathology Tests
export const DEFAULT_DIAGNOSTIC_TESTS: CatalogItemTemplate[] = [
  // Pathology & Blood
  {
    id: "test-cbc",
    code: "PATH-CBC",
    name: "Complete Blood Count (CBC) with ESR",
    type: "DIAGNOSTIC_TEST",
    category: "Pathology & Blood Tests",
    defaultPrice: 450,
    defaultDiscountPrice: 400,
    sampleType: "Blood",
    deliveryTime: "3-4 Hours (Same Day)",
    preparation: "No special fasting required. Stay hydrated.",
    homeSampleAvailable: true,
    description: "Evaluates overall health, detecting anemia, infections, leukemia, and platelet disorders.",
    iconName: "FlaskConical",
  },
  {
    id: "test-lipid",
    code: "PATH-LIPID",
    name: "Lipid Profile (Cholesterol, HDL, LDL, Triglycerides)",
    type: "DIAGNOSTIC_TEST",
    category: "Pathology & Blood Tests",
    defaultPrice: 1100,
    defaultDiscountPrice: 950,
    sampleType: "Blood",
    deliveryTime: "Same Day (4-6 Hours)",
    preparation: "Strict 10-12 hours overnight fasting required. Water is permitted.",
    homeSampleAvailable: true,
    description: "Measures blood fats to evaluate cardiovascular risk, stroke propensity, and arterial plaque health.",
    iconName: "FlaskConical",
  },
  {
    id: "test-hba1c",
    code: "PATH-HBA1C",
    name: "HbA1c (Glycated Hemoglobin)",
    type: "DIAGNOSTIC_TEST",
    category: "Pathology & Blood Tests",
    defaultPrice: 900,
    defaultDiscountPrice: 800,
    sampleType: "Blood",
    deliveryTime: "3-4 Hours",
    preparation: "No fasting required. Can be done anytime of day.",
    homeSampleAvailable: true,
    description: "Measures average blood sugar levels over the past 3 months for diabetic diagnosis and monitoring.",
    iconName: "FlaskConical",
  },
  {
    id: "test-fbs",
    code: "PATH-FBS",
    name: "Fasting Blood Sugar (FBS) & 2h ABF",
    type: "DIAGNOSTIC_TEST",
    category: "Pathology & Blood Tests",
    defaultPrice: 300,
    defaultDiscountPrice: 250,
    sampleType: "Blood",
    deliveryTime: "2-3 Hours",
    preparation: "8-10 hours fasting for the first sample, then 2 hours after breakfast for the second sample.",
    homeSampleAvailable: true,
    description: "Evaluates insulin glucose metabolism and monitors diabetes mellitus.",
    iconName: "FlaskConical",
  },
  {
    id: "test-tft",
    code: "PATH-TFT",
    name: "Thyroid Profile (TSH, FT3, FT4)",
    type: "DIAGNOSTIC_TEST",
    category: "Pathology & Blood Tests",
    defaultPrice: 1600,
    defaultDiscountPrice: 1400,
    sampleType: "Blood",
    deliveryTime: "Same Day (Evening)",
    preparation: "Morning sample preferred before taking thyroid medications unless advised by physician.",
    homeSampleAvailable: true,
    description: "Assesses thyroid gland function, hyperthyroidism, hypothyroidism, and metabolic regulation.",
    iconName: "FlaskConical",
  },
  {
    id: "test-creat",
    code: "PATH-RFT",
    name: "Serum Creatinine & Kidney Function (RFT)",
    type: "DIAGNOSTIC_TEST",
    category: "Pathology & Blood Tests",
    defaultPrice: 550,
    defaultDiscountPrice: 500,
    sampleType: "Blood",
    deliveryTime: "2-3 Hours",
    preparation: "Avoid excessive meat consumption 24 hours prior. Normal hydration.",
    homeSampleAvailable: true,
    description: "Evaluates renal clearance and kidney filtration efficiency.",
    iconName: "FlaskConical",
  },
  {
    id: "test-lft",
    code: "PATH-LFT",
    name: "Liver Function Test (SGPT, SGOT, Bilirubin, Alk Phos)",
    type: "DIAGNOSTIC_TEST",
    category: "Pathology & Blood Tests",
    defaultPrice: 1200,
    defaultDiscountPrice: 1050,
    sampleType: "Blood",
    deliveryTime: "4-5 Hours",
    preparation: "Overnight fasting of 8 hours recommended.",
    homeSampleAvailable: true,
    description: "Screens for liver inflammation, hepatitis, fatty liver, jaundice, and biliary clearance.",
    iconName: "FlaskConical",
  },
  {
    id: "test-vitd",
    code: "PATH-VITD",
    name: "Vitamin D (25-Hydroxy) & Vitamin B12",
    type: "DIAGNOSTIC_TEST",
    category: "Pathology & Blood Tests",
    defaultPrice: 3200,
    defaultDiscountPrice: 2800,
    sampleType: "Blood",
    deliveryTime: "24 Hours",
    preparation: "Fasting not mandatory.",
    homeSampleAvailable: true,
    description: "Crucial for bone density, nerve transmission, immunity, and chronic fatigue evaluation.",
    iconName: "FlaskConical",
  },
  {
    id: "test-urine",
    code: "PATH-URINE",
    name: "Urine Routine & Microscopic Examination (R/M/E)",
    type: "DIAGNOSTIC_TEST",
    category: "Pathology & Blood Tests",
    defaultPrice: 250,
    defaultDiscountPrice: 200,
    sampleType: "Urine",
    deliveryTime: "2 Hours",
    preparation: "Clean-catch midstream urine sample in sterile container.",
    homeSampleAvailable: true,
    description: "Screens for urinary tract infections (UTI), proteinuria, hematuria, and renal calculi.",
    iconName: "FlaskConical",
  },
  {
    id: "test-dengue",
    code: "PATH-DENGUE",
    name: "Dengue NS1 Antigen & IgM / IgG Antibody",
    type: "DIAGNOSTIC_TEST",
    category: "Pathology & Blood Tests",
    defaultPrice: 800,
    defaultDiscountPrice: 700,
    sampleType: "Blood",
    deliveryTime: "1-2 Hours Rapid",
    preparation: "Immediate testing recommended upon onset of high fever and joint pain.",
    homeSampleAvailable: true,
    description: "Gold standard rapid serology test to detect acute dengue viral infection and antibody response.",
    iconName: "FlaskConical",
  },
  {
    id: "test-crp",
    code: "PATH-CRP",
    name: "hs-CRP (High-Sensitivity C-Reactive Protein)",
    type: "DIAGNOSTIC_TEST",
    category: "Pathology & Blood Tests",
    defaultPrice: 650,
    defaultDiscountPrice: 550,
    sampleType: "Blood",
    deliveryTime: "3-4 Hours",
    preparation: "No fasting required.",
    homeSampleAvailable: true,
    description: "Highly sensitive marker of systemic inflammation and arterial vascular disease risk.",
    iconName: "FlaskConical",
  },
  {
    id: "test-uric",
    code: "PATH-URIC",
    name: "Serum Uric Acid (Gout Screening)",
    type: "DIAGNOSTIC_TEST",
    category: "Pathology & Blood Tests",
    defaultPrice: 400,
    defaultDiscountPrice: 350,
    sampleType: "Blood",
    deliveryTime: "2-3 Hours",
    preparation: "Avoid alcohol and high-purine foods (red meat, shellfish) 24 hours prior.",
    homeSampleAvailable: true,
    description: "Aids in diagnosing gout, hyperuricemia, and monitoring kidney stone recurrence.",
    iconName: "FlaskConical",
  },
  {
    id: "test-electrolytes",
    code: "PATH-ELECT",
    name: "Serum Electrolytes (Na+, K+, Cl-, HCO3-)",
    type: "DIAGNOSTIC_TEST",
    category: "Pathology & Blood Tests",
    defaultPrice: 850,
    defaultDiscountPrice: 750,
    sampleType: "Blood",
    deliveryTime: "2-3 Hours",
    preparation: "Standard blood draw.",
    homeSampleAvailable: true,
    description: "Essential for fluid balance, kidney failure monitoring, and cardiac rhythm stability.",
    iconName: "FlaskConical",
  },

  // Radiology & Digital Imaging
  {
    id: "test-xray-chest",
    code: "RAD-XRAY-CH",
    name: "Digital X-Ray Chest P/A View (High Resolution)",
    type: "DIAGNOSTIC_TEST",
    category: "Radiology & Imaging",
    defaultPrice: 600,
    defaultDiscountPrice: 500,
    sampleType: "Digital Imaging",
    deliveryTime: "1-2 Hours",
    preparation: "Remove metallic ornaments, jewelry, and metal-containing garments.",
    homeSampleAvailable: false,
    description: "Evaluates lungs, ribs, diaphragmatic contour, cardiomegaly, pneumonia, and tuberculosis.",
    iconName: "Sparkles",
  },
  {
    id: "test-mri-brain",
    code: "RAD-MRI-BR",
    name: "MRI Brain (1.5 Tesla / 3.0 Tesla High-Field)",
    type: "DIAGNOSTIC_TEST",
    category: "Radiology & Imaging",
    defaultPrice: 6500,
    defaultDiscountPrice: 5800,
    sampleType: "Digital Imaging",
    deliveryTime: "Same Day (4-6 Hours)",
    preparation: "No metallic implants, pacemakers, or piercings. 4 hours fasting if contrast indicated.",
    homeSampleAvailable: false,
    description: "Precision non-radiation imaging for neurological disorders, stroke, migraines, tumors, and aneurysms.",
    iconName: "Sparkles",
  },
  {
    id: "test-ct-chest",
    code: "RAD-CT-CH",
    name: "HRCT of Chest & Lungs (High Resolution CT)",
    type: "DIAGNOSTIC_TEST",
    category: "Radiology & Imaging",
    defaultPrice: 5200,
    defaultDiscountPrice: 4600,
    sampleType: "Digital Imaging",
    deliveryTime: "3-4 Hours",
    preparation: "4 hours fasting if intravenous contrast is prescribed by doctor.",
    homeSampleAvailable: false,
    description: "Detailed thin-slice volumetric pulmonary scanning for interstitial lung disease, asthma, and fibrosis.",
    iconName: "Sparkles",
  },
  {
    id: "test-ct-brain",
    code: "RAD-CT-HEAD",
    name: "CT Scan of Brain / Head (Plain)",
    type: "DIAGNOSTIC_TEST",
    category: "Radiology & Imaging",
    defaultPrice: 4200,
    defaultDiscountPrice: 3800,
    sampleType: "Digital Imaging",
    deliveryTime: "2 Hours",
    preparation: "Quick non-invasive head scan.",
    homeSampleAvailable: false,
    description: "Rapid trauma assessment for head injury, acute intracranial hemorrhage, and cerebral edema.",
    iconName: "Sparkles",
  },
  {
    id: "test-mri-spine",
    code: "RAD-MRI-LS",
    name: "MRI Lumbo-Sacral (L/S) Spine",
    type: "DIAGNOSTIC_TEST",
    category: "Radiology & Imaging",
    defaultPrice: 6500,
    defaultDiscountPrice: 5800,
    sampleType: "Digital Imaging",
    deliveryTime: "Same Day",
    preparation: "Remove all magnetic objects.",
    homeSampleAvailable: false,
    description: "Evaluates disc herniation (PLID), sciatica, spinal cord compression, and vertebral degeneration.",
    iconName: "Sparkles",
  },

  // Cardiology
  {
    id: "test-ecg",
    code: "CARD-ECG",
    name: "12-Lead Digital ECG (Electrocardiogram)",
    type: "DIAGNOSTIC_TEST",
    category: "Cardiology & Heart",
    defaultPrice: 350,
    defaultDiscountPrice: 300,
    sampleType: "Non-Invasive",
    deliveryTime: "Instant (15-30 Minutes)",
    preparation: "Avoid physical exertion or caffeine immediately prior to the test.",
    homeSampleAvailable: false,
    description: "Records electrical cardiac impulses to screen for arrhythmias, ischemia, and infarction.",
    iconName: "HeartPulse",
  },
  {
    id: "test-echo",
    code: "CARD-ECHO",
    name: "2D Color Doppler Echocardiography",
    type: "DIAGNOSTIC_TEST",
    category: "Cardiology & Heart",
    defaultPrice: 2400,
    defaultDiscountPrice: 2100,
    sampleType: "Real-time Scan",
    deliveryTime: "1 Hour",
    preparation: "No fasting required. Wear comfortable loose-fitting clothing.",
    homeSampleAvailable: false,
    description: "Ultrasound assessment of cardiac valves, ejection fraction (EF%), chamber dimensions, and wall motion.",
    iconName: "HeartPulse",
  },
  {
    id: "test-ett",
    code: "CARD-ETT",
    name: "Exercise Tolerance Test (ETT / Treadmill Stress Test)",
    type: "DIAGNOSTIC_TEST",
    category: "Cardiology & Heart",
    defaultPrice: 2800,
    defaultDiscountPrice: 2500,
    sampleType: "Non-Invasive",
    deliveryTime: "Same Day",
    preparation: "Wear athletic footwear and comfortable garments. Light meal 2-3 hours prior.",
    homeSampleAvailable: false,
    description: "Measures cardiac performance, reserve, and ischemic threshold during graded exertion.",
    iconName: "HeartPulse",
  },

  // Ultrasound (USG)
  {
    id: "test-usg-abd",
    code: "USG-ABD",
    name: "USG of Whole Abdomen with Pelvis",
    type: "DIAGNOSTIC_TEST",
    category: "Ultrasound (USG)",
    defaultPrice: 1600,
    defaultDiscountPrice: 1400,
    sampleType: "Real-time Scan",
    deliveryTime: "1-2 Hours",
    preparation: "Fasting for 6 hours prior. Drink 4-5 glasses of water 1 hour prior to keep bladder full.",
    homeSampleAvailable: false,
    description: "Examines liver, gallbladder, pancreas, spleen, kidneys, urinary bladder, prostate, and uterus.",
    iconName: "Activity",
  },
  {
    id: "test-usg-preg",
    code: "USG-PREG",
    name: "4D Pregnancy Anomaly Scan & Color Doppler",
    type: "DIAGNOSTIC_TEST",
    category: "Ultrasound (USG)",
    defaultPrice: 2600,
    defaultDiscountPrice: 2300,
    sampleType: "Real-time Scan",
    deliveryTime: "Same Day",
    preparation: "Full bladder required during first trimester. Moderate hydration later in pregnancy.",
    homeSampleAvailable: false,
    description: "High-resolution fetal anatomical survey to confirm developmental milestones and placental flow.",
    iconName: "Activity",
  },
  {
    id: "test-usg-breast",
    code: "USG-BREAST",
    name: "USG of Both Breasts (Bilateral Breast Scan)",
    type: "DIAGNOSTIC_TEST",
    category: "Ultrasound (USG)",
    defaultPrice: 1800,
    defaultDiscountPrice: 1600,
    sampleType: "Real-time Scan",
    deliveryTime: "1 Hour",
    preparation: "No deodorant or powder on chest area before scanning.",
    homeSampleAvailable: false,
    description: "Screens for fibroadenoma, breast cysts, masses, and axillary lymphadenopathy.",
    iconName: "Activity",
  },

  // Specialized & Endoscopy
  {
    id: "test-endo",
    code: "GI-ENDO",
    name: "Video Upper GI Endoscopy",
    type: "DIAGNOSTIC_TEST",
    category: "Specialized & Endoscopy",
    defaultPrice: 3800,
    defaultDiscountPrice: 3400,
    sampleType: "Non-Invasive",
    deliveryTime: "Same Day",
    preparation: "Strict overnight fasting for at least 8 hours. No liquids in morning.",
    homeSampleAvailable: false,
    description: "Direct optical visualization of esophagus, stomach, and duodenum for ulcers and reflux.",
    iconName: "Sparkles",
  },
  {
    id: "test-colonoscopy",
    code: "GI-COLON",
    name: "Video Full Colonoscopy with Biopsy",
    type: "DIAGNOSTIC_TEST",
    category: "Specialized & Endoscopy",
    defaultPrice: 5500,
    defaultDiscountPrice: 4800,
    sampleType: "Non-Invasive",
    deliveryTime: "Same Day",
    preparation: "Bowel preparation solution prescribed 1 day prior. Fasting on test morning.",
    homeSampleAvailable: false,
    description: "Comprehensive mucosal evaluation of large intestine, polyps, inflammatory bowel disease (IBD).",
    iconName: "Sparkles",
  },

  // Health Packages
  {
    id: "test-pkg-exec",
    code: "PKG-EXEC",
    name: "Executive Comprehensive Health Checkup Package",
    type: "DIAGNOSTIC_TEST",
    category: "Health Packages",
    defaultPrice: 5800,
    defaultDiscountPrice: 4500,
    sampleType: "Blood",
    deliveryTime: "24 Hours (Full Report + Doctor Review)",
    preparation: "10-12 hours overnight fasting. First morning urine required.",
    homeSampleAvailable: true,
    description: "Includes: CBC, Lipid Profile, Liver Panel, Kidney Panel, HbA1c, Thyroid (TSH), Serum Uric Acid, Urine R/M/E, Digital ECG, and Chest X-Ray.",
    iconName: "Sparkles",
  },
  {
    id: "test-pkg-heart",
    code: "PKG-HEART",
    name: "Cardiovascular Cardiac Health Screening Panel",
    type: "DIAGNOSTIC_TEST",
    category: "Health Packages",
    defaultPrice: 4900,
    defaultDiscountPrice: 3900,
    sampleType: "Blood",
    deliveryTime: "Same Day",
    preparation: "Overnight fasting 10-12 hours.",
    homeSampleAvailable: true,
    description: "Includes: Digital ECG, 2D Color Echo, Lipid Profile, Blood Glucose, Serum Creatinine, Electrolytes, and Cardiologist Consultation.",
    iconName: "HeartPulse",
  },
  {
    id: "test-pkg-diabetic",
    code: "PKG-DIABETES",
    name: "Comprehensive Diabetes Care & Microvascular Profile",
    type: "DIAGNOSTIC_TEST",
    category: "Health Packages",
    defaultPrice: 3600,
    defaultDiscountPrice: 2900,
    sampleType: "Blood",
    deliveryTime: "Same Day",
    preparation: "Fasting 8-10 hours, followed by 2 hours post-breakfast test.",
    homeSampleAvailable: true,
    description: "Includes: Fasting Sugar, 2h Post-Meal Sugar, HbA1c, Urine Microalbumin, Serum Creatinine, and Lipid Profile.",
    iconName: "FlaskConical",
  },
];

// Combined Master Template Catalog
export const ALL_CATALOG_TEMPLATES: CatalogItemTemplate[] = [
  ...DEFAULT_CLINICAL_SERVICES,
  ...DEFAULT_DIAGNOSTIC_TESTS,
];

export const CATALOG_CATEGORIES = [
  "All Categories",
  "Emergency & Critical Care",
  "Specialized Medical Services",
  "Pediatric & Maternal Care",
  "Clinical Laboratory & Blood",
  "Pharmacy & Dispensary",
  "Rehabilitation & Therapy",
  "Surgical Suites",
  "Home Health Care",
  "Insurance & Billing",
  "Pathology & Blood Tests",
  "Radiology & Imaging",
  "Cardiology & Heart",
  "Ultrasound (USG)",
  "Specialized & Endoscopy",
  "Health Packages",
] as const;
